require "calum.globals"
require "calum.options"
require "calum.keymaps"
require "calum.plugins"
require "calum.colorscheme"
require "calum.cmp"
require "calum.lsp"
require "calum.telescope"
require "calum.treesitter"
require "calum.autopairs"
require "calum.comment"
require "calum.gitsigns"
require "calum.nvimtree"
require "calum.bufferline"
require "calum.lualine"
require "calum.toggleterm"

